// WS2 build-time stats module. Computes every headline figure from the city
// containers so nothing on the site is hand-typed (brief Principle 1). Writes
// src/generated/stats.json, imported by the landing + anywhere stats appear.
// Runs before `vite build`. Vegas is a portal (no container) → excluded from counts.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/city-data.mjs";

const modular = path.join(ROOT, "cities-modular");
const slugs = readdirSync(modular).filter((d) => existsSync(path.join(modular, d, "config.json")));

const perCity = {};
const walls = []; // combined-wall manifest for the homepage travel wall
let businesses = 0, deals = 0, events = 0, nodes = 0;
for (const slug of slugs) {
  const cfg = JSON.parse(readFileSync(path.join(modular, slug, "config.json"), "utf8"));
  const n = (f) => JSON.parse(readFileSync(path.join(modular, slug, `${f}.json`), "utf8")).length;
  const b = n("directory");
  perCity[slug] = b;
  businesses += b;
  deals += n("deals");
  events += n("events");
  nodes += n("concierge");

  const img = cfg.images ?? {};
  const files = [img.hero, ...(img.wall ?? []), ...(img.story ?? [])].filter(Boolean);
  walls.push({
    slug,
    name: cfg.name,
    // a few travel photos per city, as absolute engine paths
    photos: [...new Set(files)].slice(0, 5).map((f) => `/cities/${slug}/images/${f}`),
  });
}

const stats = {
  _comment: "Generated by scripts/gen-stats.mjs at build time — do not edit. Every displayed statistic derives from here (WS2 truth pass).",
  cities: slugs.length,
  businesses,
  deals,
  events,
  nodes,
  perCity,
  walls,
};

const outDir = path.join(ROOT, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "stats.json"), JSON.stringify(stats, null, 2) + "\n");
// Also expose a served copy at /stats.json so static pages (WS4 DMO pitch page,
// the build-time one-pager PDF) can read the same computed numbers — never drifts.
const pubDir = path.join(ROOT, "public");
if (existsSync(pubDir)) writeFileSync(path.join(pubDir, "stats.json"), JSON.stringify(stats, null, 2) + "\n");
console.log(`✓ stats: ${stats.cities} cities · ${businesses.toLocaleString()} businesses · ${nodes} nodes → src/generated/stats.json (+ public/stats.json)`);
