// WS2 service worker — generated post-build with a per-deploy version so clients
// never get pinned to stale data (the legacy SW's failure mode). Strategy:
//   • navigations + JSON (HTML, city data) → NETWORK-FIRST (fresh within one nav),
//     fall back to cache offline
//   • hashed /assets/* → CACHE-FIRST (immutable, content-hashed by Vite)
//   • everything else → network, cache fallback
// Precaches the app shell so a saved city works offline.
import { writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/city-data.mjs";

const dist = path.join(ROOT, "dist");
if (!existsSync(dist)) throw new Error("run after vite build (dist/ missing)");

const version = `lt-${Date.now().toString(36)}`; // unique per deploy → old caches evicted

const sw = `// GENERATED by scripts/gen-sw.mjs — do not edit. Version stamped per deploy.
const VERSION = ${JSON.stringify(version)};
const SHELL = ["/", "/index.html", "/manifest.webmanifest"];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // don't touch cross-origin (fonts, videos CDN, etc.)

  // Immutable hashed build assets → cache-first
  if (url.pathname.startsWith("/assets/")) {
    e.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(VERSION).then((c) => c.put(req, copy));
        return res;
      }))
    );
    return;
  }

  // HTML navigations + JSON data → network-first (freshness), cache fallback (offline)
  const isDoc = req.mode === "navigate" || url.pathname.endsWith(".json") || url.pathname.endsWith(".html") || url.pathname === "/";
  if (isDoc) {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(VERSION).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match("/")))
    );
    return;
  }

  // Images / everything else → cache-first with network fill
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      const copy = res.clone();
      caches.open(VERSION).then((c) => c.put(req, copy));
      return res;
    }).catch(() => hit))
  );
});
`;

writeFileSync(path.join(dist, "service-worker.js"), sw);
console.log(`✓ service worker ${version} → dist/service-worker.js (network-first HTML/data, cache-first assets)`);
