// WS2 build-time stats module. Computes every headline figure from the city
// containers so nothing on the site is hand-typed (brief Principle 1). Writes
// src/generated/stats.json, imported by the landing + anywhere stats appear.
// Runs before `vite build`. Vegas is a portal (no container) → excluded from counts.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/city-data.mjs";

const modular = path.join(ROOT, "cities-modular");
const slugs = readdirSync(modular).filter((d) => existsSync(path.join(modular, d, "config.json")));

const perCity = {};
let businesses = 0, deals = 0, events = 0, nodes = 0;
for (const slug of slugs) {
  const n = (f) => JSON.parse(readFileSync(path.join(modular, slug, `${f}.json`), "utf8")).length;
  const b = n("directory");
  perCity[slug] = b;
  businesses += b;
  deals += n("deals");
  events += n("events");
  nodes += n("concierge");
}

const stats = {
  _comment: "Generated by scripts/gen-stats.mjs at build time — do not edit. Every displayed statistic derives from here (WS2 truth pass).",
  cities: slugs.length,
  businesses,
  deals,
  events,
  nodes,
  perCity,
};

const outDir = path.join(ROOT, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "stats.json"), JSON.stringify(stats, null, 2) + "\n");
console.log(`✓ stats: ${stats.cities} cities · ${businesses.toLocaleString()} businesses · ${nodes} nodes → src/generated/stats.json`);
