// WS2 service worker — generated post-build with a per-deploy version so clients
// never get pinned to stale data (the legacy SW's failure mode). Strategy:
//   • navigations + JSON (HTML, city data) → NETWORK-FIRST (fresh within one nav),
//     fall back to cache offline
//   • hashed /assets/* → CACHE-FIRST (immutable, content-hashed by Vite)
//   • everything else → network, cache fallback
// Precaches the app shell so a saved city works offline.
import { writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/city-data.mjs";

const dist = path.join(ROOT, "dist");
if (!existsSync(dist)) throw new Error("run after vite build (dist/ missing)");

const version = `lt-${Date.now().toString(36)}`; // unique per deploy → old caches evicted

const sw = `// GENERATED by scripts/gen-sw.mjs — do not edit. Version stamped per deploy.
const VERSION = ${JSON.stringify(version)};
const SHELL = ["/", "/index.html", "/manifest.webmanifest"];
// Stable, un-versioned cache for an explicitly "saved" city (see SaveCity.jsx).
// Survives per-deploy VERSION churn so the saved trip keeps working offline.
const SAVED = "lt-saved-city";

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      // Evict prior VERSION caches, but never the saved-city cache (kept across deploys).
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION && k !== SAVED).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Save-this-city: on {type:"SAVE_CITY", assets:[urls]} pin the given URLs into the
// stable SAVED cache so they resolve offline; reply {type:"CITY_SAVED"} to the sender
// (or {type:"SAVE_FAILED"} if any asset couldn't be fetched). addAll is all-or-nothing.
self.addEventListener("message", (e) => {
  const data = e.data || {};
  if (data.type !== "SAVE_CITY") return;
  const assets = Array.isArray(data.assets) ? data.assets.filter(Boolean) : [];
  const reply = (msg) => {
    if (e.source && e.source.postMessage) e.source.postMessage(msg);
    else self.clients.matchAll().then((cs) => cs.forEach((c) => c.postMessage(msg)));
  };
  e.waitUntil(
    caches.open(SAVED)
      .then((c) => c.addAll(assets))
      .then(() => reply({ type: "CITY_SAVED", count: assets.length }))
      .catch((err) => reply({ type: "SAVE_FAILED", error: String((err && err.message) || err) }))
  );
});

self.addEventListener("fetch", (e) => {
  // Every branch below resolves cache hits via the global caches.match(req), which
  // scans ALL caches (VERSION + SAVED) in order — so once a URL is pinned into SAVED
  // it is served offline through the existing cache-first / network-first fallbacks,
  // no per-strategy change needed.
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // don't touch cross-origin (fonts, videos CDN, etc.)

  // Immutable hashed build assets → cache-first
  if (url.pathname.startsWith("/assets/")) {
    e.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(VERSION).then((c) => c.put(req, copy));
        return res;
      }))
    );
    return;
  }

  // HTML navigations + JSON data → network-first (freshness), cache fallback (offline)
  const isDoc = req.mode === "navigate" || url.pathname.endsWith(".json") || url.pathname.endsWith(".html") || url.pathname === "/";
  if (isDoc) {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(VERSION).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match("/")))
    );
    return;
  }

  // Images / everything else → cache-first with network fill
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      const copy = res.clone();
      caches.open(VERSION).then((c) => c.put(req, copy));
      return res;
    }).catch(() => hit))
  );
});
`;

writeFileSync(path.join(dist, "service-worker.js"), sw);
console.log(`✓ service worker ${version} → dist/service-worker.js (network-first HTML/data, cache-first assets)`);
